fixes opam spec for homebrew (#652)
* fixes opam spec for homebrew

This will theoretically move us closer to the goal of passing tests on
the Travis Mac OS X box.

* switches to llvm38 in homebrew

It looks like that llvm-3.4 is no longer brewed in the house:

OS package update successful
Error: No available formula with the name "homebrew/versions/llvm34"
==> Searching for a previously deleted formula...
homebrew/versions/llvm34 was deleted from homebrew/versions in commit f85a081:
  llvm*: migrate to homebrew/core. (https://github.com/Homebrew/homebrew-versions/issues/1475)
  Also, delete `llvm-gcc28`, `llvm33` as they have very few installs from
  analytics.