fixes nightly tests
Our nightly tests on macOS fail with the next error while
executing `opam depext -u bap` command:
```
Error: python@3.8 3.8.4 is already installed
To upgrade to 3.8.5, run `brew upgrade python@3.8`.
```
The `-u` flag in `opam depext -u bap` updates OS packages sets.
In this case, `brew` becomes aware of the new available python version.
Then, `opam depext` calls `brew install` with all the packages
we depend on including `python`.

`macOS` on GHA comes with preinstalled `python 3.8.4` formula and
the problem is that `brew install` fails if another version of the same
formula is installed. The github runner detects a non-zero exit code
and the whole workflow is failed.

This PR fixes this problem by upgrading all the installed formulae
via `brew update && brew upgrade` before calling `opam depext -u bap`. Now we can be
sure that all the system packages we depend on have the most modern versions.